name: TimeEdit Merger
version: "0.0.4"
slug: timeedit_merger
description: Merges multiple TimeEdit schedules into one unified schedule. Supports filtering by activities and ensures that all ics fields are populated correctly.

startup: application
boot: auto

arch:
  - amd64
  - aarch64

ingress: true
ingress_port: 8080

panel_title: TimeEdit Merger
panel_icon: mdi:calendar-multiple

ports:
  8080/tcp: null

ports_description:
  8080/tcp: Web interface

options:
    admin_token: null
    feed_tokens: null
    refresh_minutes: 5
    timeout_seconds: 10
    lookahead_days: 30
    categories:
        - föreläsning
        - handledning
        - räkneövning
        - seminarium
        - datorlaboration
    output1:
        name: Private
        salt: null
        enabled: true
    output2:
        name: Public
        salt: null
        enabled: false
schema:
  admin_token: "str?"
  feed_tokens: "str?"
  refresh_minutes: int(1,1440)
  timeout_seconds: int(1,60)
  lookahead_days: int(1,120)
  categories: list(str)
  output1:
    name: str
    salt: "str?"
    enabled: bool
  output2:
    name: str
    salt: "str?"
    enabled: bool

url: https://github.com/saud0227/timeedit-merger